//! Build script for TextBank
//!
//! This script generates Rust code from Protocol Buffer definitions during compilation.
//! It uses tonic-build to generate both client and server code from the gRPC service definition.

/// Main build function that generates Rust code from protobuf definitions.
///
/// This function:
/// 1. Configures tonic-build to generate server code (client code is generated by default)
/// 2. Compiles the text_bank.proto file into Rust structs and trait implementations
/// 3. Makes the generated code available via the `pb` module in main.rs
///
/// The generated code includes:
/// - Message structs for all protobuf messages
/// - Service trait for implementing the gRPC server
/// - Client struct for making gRPC calls
///
/// # Panics
/// Panics if protobuf compilation fails, which would indicate:
/// - Missing proto files
/// - Invalid protobuf syntax
/// - Missing protoc compiler
fn main() {
    tonic_build::configure()
        .build_server(true) // Generate server-side code
        .compile_protos(
            &["proto/text_bank.proto"], // Proto files to compile
            &["proto"],                 // Include directories
        )
        .expect("Failed to compile protobuf files");
}
